#define PERIODIC 
#define PMGRID 512
#define MULTIPLEDOMAINS 8
#define PEANOHILBERT 
#define WALLCLOCK 
#define MYSORT 
#define DOUBLEPRECISION 2
#define DOUBLEPRECISION_FFTW 
#define FOF 
#define FOF_PRIMARY_LINK_TYPES 2
#define FOF_GROUP_MIN_LEN 20
#define SUBFIND 
#define SUBFIND_SAVE_PARTICLELISTS 
#define SO_VEL_DISPERSIONS 
#define LINKLENGTH 0.2
#define NO_ISEND_IRECV_IN_DOMAIN 
#define FIX_PATHSCALE_MPI_STATUS_IGNORE_BUG 
