CREATE TABLE GALAXIES (
 type INTEGER NOT NULL 
,  haloIndex INTEGER NOT NULL 
,  snapNum INTEGER NOT NULL 
,  lookBackTimeToSnap REAL NOT NULL 
,  centralMvir REAL NOT NULL 
,  pos_1 REAL NOT NULL 
,  pos_2 REAL NOT NULL 
,  pos_3 REAL NOT NULL 
,  vel_1 REAL NOT NULL 
,  vel_2 REAL NOT NULL 
,  vel_3 REAL NOT NULL 
,  len INTEGER NOT NULL 
,  mvir REAL NOT NULL 
,  rvir REAL NOT NULL 
,  vvir REAL NOT NULL 
,  vmax REAL NOT NULL 
,  gasSpin_1 REAL NOT NULL 
,  gasSpin_2 REAL NOT NULL 
,  gasSpin_3 REAL NOT NULL 
,  stellarSpin_1 REAL NOT NULL 
,  stellarSpin_2 REAL NOT NULL 
,  stellarSpin_3 REAL NOT NULL 
,  infallVmax REAL NOT NULL 
,  infallSnap INTEGER NOT NULL 
,  hotRadius REAL NOT NULL 
,  oriMergTime REAL NOT NULL 
,  mergTime REAL NOT NULL 
,  distanceToCentralGal_1 REAL NOT NULL 
,  distanceToCentralGal_2 REAL NOT NULL 
,  distanceToCentralGal_3 REAL NOT NULL 
,  coldGas REAL NOT NULL 
,  bulgeMass REAL NOT NULL 
,  diskMass REAL NOT NULL 
,  hotGas REAL NOT NULL 
,  ejectedMass REAL NOT NULL 
,  blackHoleMass REAL NOT NULL 
,  blackHoleGas REAL NOT NULL 
,  iCM REAL NOT NULL 
,  metalsColdGas REAL NOT NULL 
,  metalsBulgeMass REAL NOT NULL 
,  metalsDiskMass REAL NOT NULL 
,  metalsHotGas REAL NOT NULL 
,  metalsEjectedMass REAL NOT NULL 
,  metalsICM REAL NOT NULL 
,  sfr REAL NOT NULL 
,  sfrBulge REAL NOT NULL 
,  xrayLum REAL NOT NULL 
,  bulgeSize REAL NOT NULL 
,  stellarDiskRadius REAL NOT NULL 
,  gasDiskRadius REAL NOT NULL 
,  cosInclination REAL NOT NULL 
,  disruptOn INTEGER NOT NULL 
,  mergeOn INTEGER NOT NULL 
,  coolingRadius REAL NOT NULL 
,  quasarAccretionRate REAL NOT NULL 
,  radioAccretionRate REAL NOT NULL 
,  mag_1 REAL NOT NULL 
,  mag_2 REAL NOT NULL 
,  mag_3 REAL NOT NULL 
,  mag_4 REAL NOT NULL 
,  mag_5 REAL NOT NULL 
,  mag_6 REAL NOT NULL 
,  mag_7 REAL NOT NULL 
,  mag_8 REAL NOT NULL 
,  mag_9 REAL NOT NULL 
,  mag_10 REAL NOT NULL 
,  mag_11 REAL NOT NULL 
,  mag_12 REAL NOT NULL 
,  mag_13 REAL NOT NULL 
,  mag_14 REAL NOT NULL 
,  mag_15 REAL NOT NULL 
,  magBulge_1 REAL NOT NULL 
,  magBulge_2 REAL NOT NULL 
,  magBulge_3 REAL NOT NULL 
,  magBulge_4 REAL NOT NULL 
,  magBulge_5 REAL NOT NULL 
,  magBulge_6 REAL NOT NULL 
,  magBulge_7 REAL NOT NULL 
,  magBulge_8 REAL NOT NULL 
,  magBulge_9 REAL NOT NULL 
,  magBulge_10 REAL NOT NULL 
,  magBulge_11 REAL NOT NULL 
,  magBulge_12 REAL NOT NULL 
,  magBulge_13 REAL NOT NULL 
,  magBulge_14 REAL NOT NULL 
,  magBulge_15 REAL NOT NULL 
,  magDust_1 REAL NOT NULL 
,  magDust_2 REAL NOT NULL 
,  magDust_3 REAL NOT NULL 
,  magDust_4 REAL NOT NULL 
,  magDust_5 REAL NOT NULL 
,  magDust_6 REAL NOT NULL 
,  magDust_7 REAL NOT NULL 
,  magDust_8 REAL NOT NULL 
,  magDust_9 REAL NOT NULL 
,  magDust_10 REAL NOT NULL 
,  magDust_11 REAL NOT NULL 
,  magDust_12 REAL NOT NULL 
,  magDust_13 REAL NOT NULL 
,  magDust_14 REAL NOT NULL 
,  magDust_15 REAL NOT NULL 
,  massWeightAge REAL NOT NULL 
,  sfh_ibin INTEGER NOT NULL 
,  sfh_time_1 REAL NOT NULL 
,  sfh_time_2 REAL NOT NULL 
,  sfh_time_3 REAL NOT NULL 
,  sfh_time_4 REAL NOT NULL 
,  sfh_time_5 REAL NOT NULL 
,  sfh_time_6 REAL NOT NULL 
,  sfh_time_7 REAL NOT NULL 
,  sfh_time_8 REAL NOT NULL 
,  sfh_time_9 REAL NOT NULL 
,  sfh_time_10 REAL NOT NULL 
,  sfh_time_11 REAL NOT NULL 
,  sfh_time_12 REAL NOT NULL 
,  sfh_time_13 REAL NOT NULL 
,  sfh_time_14 REAL NOT NULL 
,  sfh_time_15 REAL NOT NULL 
,  sfh_time_16 REAL NOT NULL 
,  sfh_time_17 REAL NOT NULL 
,  sfh_time_18 REAL NOT NULL 
,  sfh_time_19 REAL NOT NULL 
,  sfh_dt_1 REAL NOT NULL 
,  sfh_dt_2 REAL NOT NULL 
,  sfh_dt_3 REAL NOT NULL 
,  sfh_dt_4 REAL NOT NULL 
,  sfh_dt_5 REAL NOT NULL 
,  sfh_dt_6 REAL NOT NULL 
,  sfh_dt_7 REAL NOT NULL 
,  sfh_dt_8 REAL NOT NULL 
,  sfh_dt_9 REAL NOT NULL 
,  sfh_dt_10 REAL NOT NULL 
,  sfh_dt_11 REAL NOT NULL 
,  sfh_dt_12 REAL NOT NULL 
,  sfh_dt_13 REAL NOT NULL 
,  sfh_dt_14 REAL NOT NULL 
,  sfh_dt_15 REAL NOT NULL 
,  sfh_dt_16 REAL NOT NULL 
,  sfh_dt_17 REAL NOT NULL 
,  sfh_dt_18 REAL NOT NULL 
,  sfh_dt_19 REAL NOT NULL 
,  sfh_DiskMass_1 REAL NOT NULL 
,  sfh_DiskMass_2 REAL NOT NULL 
,  sfh_DiskMass_3 REAL NOT NULL 
,  sfh_DiskMass_4 REAL NOT NULL 
,  sfh_DiskMass_5 REAL NOT NULL 
,  sfh_DiskMass_6 REAL NOT NULL 
,  sfh_DiskMass_7 REAL NOT NULL 
,  sfh_DiskMass_8 REAL NOT NULL 
,  sfh_DiskMass_9 REAL NOT NULL 
,  sfh_DiskMass_10 REAL NOT NULL 
,  sfh_DiskMass_11 REAL NOT NULL 
,  sfh_DiskMass_12 REAL NOT NULL 
,  sfh_DiskMass_13 REAL NOT NULL 
,  sfh_DiskMass_14 REAL NOT NULL 
,  sfh_DiskMass_15 REAL NOT NULL 
,  sfh_DiskMass_16 REAL NOT NULL 
,  sfh_DiskMass_17 REAL NOT NULL 
,  sfh_DiskMass_18 REAL NOT NULL 
,  sfh_DiskMass_19 REAL NOT NULL 
,  sfh_BulgeMass_1 REAL NOT NULL 
,  sfh_BulgeMass_2 REAL NOT NULL 
,  sfh_BulgeMass_3 REAL NOT NULL 
,  sfh_BulgeMass_4 REAL NOT NULL 
,  sfh_BulgeMass_5 REAL NOT NULL 
,  sfh_BulgeMass_6 REAL NOT NULL 
,  sfh_BulgeMass_7 REAL NOT NULL 
,  sfh_BulgeMass_8 REAL NOT NULL 
,  sfh_BulgeMass_9 REAL NOT NULL 
,  sfh_BulgeMass_10 REAL NOT NULL 
,  sfh_BulgeMass_11 REAL NOT NULL 
,  sfh_BulgeMass_12 REAL NOT NULL 
,  sfh_BulgeMass_13 REAL NOT NULL 
,  sfh_BulgeMass_14 REAL NOT NULL 
,  sfh_BulgeMass_15 REAL NOT NULL 
,  sfh_BulgeMass_16 REAL NOT NULL 
,  sfh_BulgeMass_17 REAL NOT NULL 
,  sfh_BulgeMass_18 REAL NOT NULL 
,  sfh_BulgeMass_19 REAL NOT NULL 
,  sfh_ICM_1 REAL NOT NULL 
,  sfh_ICM_2 REAL NOT NULL 
,  sfh_ICM_3 REAL NOT NULL 
,  sfh_ICM_4 REAL NOT NULL 
,  sfh_ICM_5 REAL NOT NULL 
,  sfh_ICM_6 REAL NOT NULL 
,  sfh_ICM_7 REAL NOT NULL 
,  sfh_ICM_8 REAL NOT NULL 
,  sfh_ICM_9 REAL NOT NULL 
,  sfh_ICM_10 REAL NOT NULL 
,  sfh_ICM_11 REAL NOT NULL 
,  sfh_ICM_12 REAL NOT NULL 
,  sfh_ICM_13 REAL NOT NULL 
,  sfh_ICM_14 REAL NOT NULL 
,  sfh_ICM_15 REAL NOT NULL 
,  sfh_ICM_16 REAL NOT NULL 
,  sfh_ICM_17 REAL NOT NULL 
,  sfh_ICM_18 REAL NOT NULL 
,  sfh_ICM_19 REAL NOT NULL 
,  sfh_MetalsDiskMass_1 REAL NOT NULL 
,  sfh_MetalsDiskMass_2 REAL NOT NULL 
,  sfh_MetalsDiskMass_3 REAL NOT NULL 
,  sfh_MetalsDiskMass_4 REAL NOT NULL 
,  sfh_MetalsDiskMass_5 REAL NOT NULL 
,  sfh_MetalsDiskMass_6 REAL NOT NULL 
,  sfh_MetalsDiskMass_7 REAL NOT NULL 
,  sfh_MetalsDiskMass_8 REAL NOT NULL 
,  sfh_MetalsDiskMass_9 REAL NOT NULL 
,  sfh_MetalsDiskMass_10 REAL NOT NULL 
,  sfh_MetalsDiskMass_11 REAL NOT NULL 
,  sfh_MetalsDiskMass_12 REAL NOT NULL 
,  sfh_MetalsDiskMass_13 REAL NOT NULL 
,  sfh_MetalsDiskMass_14 REAL NOT NULL 
,  sfh_MetalsDiskMass_15 REAL NOT NULL 
,  sfh_MetalsDiskMass_16 REAL NOT NULL 
,  sfh_MetalsDiskMass_17 REAL NOT NULL 
,  sfh_MetalsDiskMass_18 REAL NOT NULL 
,  sfh_MetalsDiskMass_19 REAL NOT NULL 
,  sfh_MetalsBulgeMass_1 REAL NOT NULL 
,  sfh_MetalsBulgeMass_2 REAL NOT NULL 
,  sfh_MetalsBulgeMass_3 REAL NOT NULL 
,  sfh_MetalsBulgeMass_4 REAL NOT NULL 
,  sfh_MetalsBulgeMass_5 REAL NOT NULL 
,  sfh_MetalsBulgeMass_6 REAL NOT NULL 
,  sfh_MetalsBulgeMass_7 REAL NOT NULL 
,  sfh_MetalsBulgeMass_8 REAL NOT NULL 
,  sfh_MetalsBulgeMass_9 REAL NOT NULL 
,  sfh_MetalsBulgeMass_10 REAL NOT NULL 
,  sfh_MetalsBulgeMass_11 REAL NOT NULL 
,  sfh_MetalsBulgeMass_12 REAL NOT NULL 
,  sfh_MetalsBulgeMass_13 REAL NOT NULL 
,  sfh_MetalsBulgeMass_14 REAL NOT NULL 
,  sfh_MetalsBulgeMass_15 REAL NOT NULL 
,  sfh_MetalsBulgeMass_16 REAL NOT NULL 
,  sfh_MetalsBulgeMass_17 REAL NOT NULL 
,  sfh_MetalsBulgeMass_18 REAL NOT NULL 
,  sfh_MetalsBulgeMass_19 REAL NOT NULL 
,  sfh_MetalsICM_1 REAL NOT NULL 
,  sfh_MetalsICM_2 REAL NOT NULL 
,  sfh_MetalsICM_3 REAL NOT NULL 
,  sfh_MetalsICM_4 REAL NOT NULL 
,  sfh_MetalsICM_5 REAL NOT NULL 
,  sfh_MetalsICM_6 REAL NOT NULL 
,  sfh_MetalsICM_7 REAL NOT NULL 
,  sfh_MetalsICM_8 REAL NOT NULL 
,  sfh_MetalsICM_9 REAL NOT NULL 
,  sfh_MetalsICM_10 REAL NOT NULL 
,  sfh_MetalsICM_11 REAL NOT NULL 
,  sfh_MetalsICM_12 REAL NOT NULL 
,  sfh_MetalsICM_13 REAL NOT NULL 
,  sfh_MetalsICM_14 REAL NOT NULL 
,  sfh_MetalsICM_15 REAL NOT NULL 
,  sfh_MetalsICM_16 REAL NOT NULL 
,  sfh_MetalsICM_17 REAL NOT NULL 
,  sfh_MetalsICM_18 REAL NOT NULL 
,  sfh_MetalsICM_19 REAL NOT NULL 
)
