#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stdint.h>

//=================================================================================
// This code aims at converting (and merging) binary _halos, _profiles,
// and _particles files generated by AHF when switching on -DAHFbinary
//
// This code also gives you the option to only convert those halo properties
// you are primarily interested in. But for that you need to adjust the
// part where the information is written commenting out those properties
// of no concern to you. Please adjust the two routines
//                   write_halos()   &   write_profiles()
// to best suit your needs. You are also able to filter out halos below a certain
// MassCut given on the commandline when starting this code.
//
// Note, none of the filtering works for _particles as this file does not contain
// any information about halo properties! Or to be more presice, fiddling with the
// _particles files is presently not supported.
//
// THIS CODE IS INDEPENDENT OF ANY AHF LIBRARY AND COULD BE COMPILED STAND-ALONE
//=================================================================================

#define VERBOSE
#define PROFILE_FOR_GNUPLOT  // will have blank lines separating each profile
#define SUSSEXBIGRUN

//===================================================================
// the headers for the ASCII output files
//===================================================================
#define HEADER_HALOS    "# up to you what to put here\n"
#define HEADER_PROFILES "# up to you what to put here\n"

//===================================================================
// global variables
//===================================================================
double MassCut; // haloes below this mass will not be written to ASCII

//===================================================================
// structures
//===================================================================
typedef uint64_t ptid_t;
typedef uint64_t hid_t;
typedef float double_t; 
typedef struct m_particle
{
  ptid_t ID;
  hid_t haloID;
} m_particle_t;

typedef struct particlelist
{
  ptid_t ID;
} particlelist_t;

typedef struct m_halo 
{
  ptid_t ID;
  double_t Mvir;
  double_t Rvir;
  double_t Xc;
  double_t Yc;
  double_t Zc;
  double_t VXc;
  double_t VYc;
  double_t VZc;
  particlelist_t *Particles;
} m_halo_t;

typedef struct halo {
  uint32_t numColumns;
  uint64_t ID;
  uint64_t hostHalo;
  uint32_t numSubStruct;
  double_t   Mvir;
  uint32_t npart;
  double_t   Xc;
  double_t   Yc;
  double_t   Zc;
  double_t   VXc;
  double_t   VYc;
  double_t   VZc;
  double_t   Rvir;
  double_t   Rmax;
  double_t   r2;
  double_t   mbp_offset;
  double_t   com_offset;
  double_t   Vmax;
  double_t   v_esc;
  double_t   sigV;
  double_t   lambda;
  double_t   lambdaE;
  double_t   Lx;
  double_t   Ly;
  double_t   Lz;
  double_t   b;
  double_t   c;
  double_t   Eax;
  double_t   Eay;
  double_t   Eaz;
  double_t   Ebx;
  double_t   Eby;
  double_t   Ebz;
  double_t   Ecx;
  double_t   Ecy;
  double_t   Ecz;
  double_t   ovdens;
  uint32_t nbins;
  double_t   fMhires;
  double_t   Ekin;
  double_t   Epot;
  double_t   SurfP;
  double_t   Phi0;
  double_t   cNFW;
  uint32_t n_gas;
  double_t   M_gas;
  double_t   lambda_gas;
  double_t   lambdaE_gas;
  double_t   Lx_gas;
  double_t   Ly_gas;
  double_t   Lz_gas;
  double_t   b_gas;
  double_t   c_gas;
  double_t   Eax_gas;
  double_t   Eay_gas;
  double_t   Eaz_gas;
  double_t   Ebx_gas;
  double_t   Eby_gas;
  double_t   Ebz_gas;
  double_t   Ecx_gas;
  double_t   Ecy_gas;
  double_t   Ecz_gas;
  double_t   Ekin_gas;
  double_t   Epot_gas;
  uint32_t n_star;
  double_t   M_star;
  double_t   lambda_star;
  double_t   lambdaE_star;
  double_t   Lx_star;
  double_t   Ly_star;
  double_t   Lz_star;
  double_t   b_star;
  double_t   c_star;
  double_t   Eax_star;
  double_t   Eay_star;
  double_t   Eaz_star;
  double_t   Ebx_star;
  double_t   Eby_star;
  double_t   Ebz_star;
  double_t   Ecx_star;
  double_t   Ecy_star;
  double_t   Ecz_star;
  double_t   Ekin_star;
  double_t   Epot_star;
  double_t   mean_z_gas;
  double_t   mean_z_star;
} halo_t;

typedef struct halo_profile {
  uint32_t      nbins;
  uint32_t      numColumns;
  double_t        *r;
  uint32_t      *npart;
  double_t        *M_in_r;
  double_t        *ovdens;
  double_t        *dens;
  double_t        *vcirc;
  double_t        *vesc;
  double_t        *sigv;
  double_t        *Lx;
  double_t        *Ly;
  double_t        *Lz;
  double_t        *b;
  double_t        *c;
  double_t        *Eax;
  double_t        *Eay;
  double_t        *Eaz;
  double_t        *Ebx;
  double_t        *Eby;
  double_t        *Ebz;
  double_t        *Ecx;
  double_t        *Ecy;
  double_t        *Ecz;
  double_t        *Ekin;
  double_t        *Epot;
  double_t        *M_gas;
  double_t        *M_star;
  double_t        *u_gas;
  double_t        *Z_gas_sh;
  double_t        *Z_star_sh;
} halo_profile_t;

//===================================================================
// PROTOTYPES
//===================================================================
void     convert                           (int , int , char **, char *);
void     convert_halos                     (FILE *, FILE *);
void     convert_profiles                  (FILE *, FILE *);
void     convert_particles                 (FILE *, FILE *);
void     alloc_profile                     (uint64_t, halo_profile_t *);
void     free_profile                      (halo_profile_t *);
uint64_t get_TotalNumHalos_from_particles  (int, char**);
void load_halo_catalogue_binary(char *halofile, char *partfile );
void  read_AHF_binary(FILE *fphalo, FILE *fppart);
//===================================================================
// routines copied from AHF to keep this code independent
//===================================================================
int     ReadULong          (FILE *, unsigned long *, int);
int     ReadInt            (FILE *, int           *, int);
int     ReadUInt           (FILE *, unsigned int  *, int);
int     ReadDouble_T         (FILE *, double_t        *, int);
#define TRUE  1
#define FALSE 0

/*=================================================================================================
 * write_halo(): FEEL FREE TO FILTER UNWANTED PROPERTIES BY COMMENTING THEM OUT
 *=================================================================================================*/
void write_halo(halo_t halo, FILE *fpout)
{
  if(halo.Mvir >= MassCut){
    fprintf(fpout,"%ld ",(long unsigned)halo.ID);
    fprintf(fpout,"%ld ",(long unsigned)halo.hostHalo);
    fprintf(fpout,"%d ",halo.numSubStruct);
    fprintf(fpout,"%g ",halo.Mvir);
    fprintf(fpout,"%d ",halo.npart);
    fprintf(fpout,"%f ",halo.Xc);
    fprintf(fpout,"%f ",halo.Yc);
    fprintf(fpout,"%f ",halo.Zc);
    fprintf(fpout,"%f ",halo.VXc);
    fprintf(fpout,"%f ",halo.VYc);
    fprintf(fpout,"%f ",halo.VZc);
    fprintf(fpout,"%f ",halo.Rvir);
    fprintf(fpout,"%f ",halo.Rmax);
    fprintf(fpout,"%f ",halo.r2);
    fprintf(fpout,"%f ",halo.mbp_offset);
    fprintf(fpout,"%f ",halo.com_offset);
    fprintf(fpout,"%f ",halo.Vmax);
    fprintf(fpout,"%f ",halo.v_esc);
    fprintf(fpout,"%f ",halo.sigV);
    fprintf(fpout,"%f ",halo.lambda);
    fprintf(fpout,"%f ",halo.lambdaE);
    fprintf(fpout,"%f ",halo.Lx);
    fprintf(fpout,"%f ",halo.Ly);
    fprintf(fpout,"%f ",halo.Lz);
    fprintf(fpout,"%f ",halo.b);
    fprintf(fpout,"%f ",halo.c);
    fprintf(fpout,"%f ",halo.Eax);
    fprintf(fpout,"%f ",halo.Eay);
    fprintf(fpout,"%f ",halo.Eaz);
    fprintf(fpout,"%f ",halo.Ebx);
    fprintf(fpout,"%f ",halo.Eby);
    fprintf(fpout,"%f ",halo.Ebz);
    fprintf(fpout,"%f ",halo.Ecx);
    fprintf(fpout,"%f ",halo.Ecy);
    fprintf(fpout,"%f ",halo.Ecz);
    fprintf(fpout,"%f ",halo.ovdens);
    fprintf(fpout,"%d ",halo.nbins);
    fprintf(fpout,"%f ",halo.fMhires);
    fprintf(fpout,"%g ",halo.Ekin);
    fprintf(fpout,"%g ",halo.Epot);
    fprintf(fpout,"%g ",halo.SurfP);
    fprintf(fpout,"%g ",halo.Phi0);
    fprintf(fpout,"%f ",halo.cNFW);
    if(halo.numColumns > 43) {
      fprintf(fpout,"%d ",halo.n_gas);
      fprintf(fpout,"%g ",halo.M_gas);
      fprintf(fpout,"%f ",halo.lambda_gas);
      fprintf(fpout,"%f ",halo.lambdaE_gas);
      fprintf(fpout,"%f ",halo.Lx_gas);
      fprintf(fpout,"%f ",halo.Ly_gas);
      fprintf(fpout,"%f ",halo.Lz_gas);
      fprintf(fpout,"%f ",halo.b_gas);
      fprintf(fpout,"%f ",halo.c_gas);
      fprintf(fpout,"%f ",halo.Eax_gas);
      fprintf(fpout,"%f ",halo.Eay_gas);
      fprintf(fpout,"%f ",halo.Eaz_gas);
      fprintf(fpout,"%f ",halo.Ebx_gas);
      fprintf(fpout,"%f ",halo.Eby_gas);
      fprintf(fpout,"%f ",halo.Ebz_gas);
      fprintf(fpout,"%f ",halo.Ecx_gas);
      fprintf(fpout,"%f ",halo.Ecy_gas);
      fprintf(fpout,"%f ",halo.Ecz_gas);
      fprintf(fpout,"%g ",halo.Ekin_gas);
      fprintf(fpout,"%g ",halo.Epot_gas);
      fprintf(fpout,"%d ",halo.n_star);
      fprintf(fpout,"%g ",halo.M_star);
      fprintf(fpout,"%f ",halo.lambda_star);
      fprintf(fpout,"%f ",halo.lambdaE_star);
      fprintf(fpout,"%f ",halo.Lx_star);
      fprintf(fpout,"%f ",halo.Ly_star);
      fprintf(fpout,"%f ",halo.Lz_star);
      fprintf(fpout,"%f ",halo.b_star);
      fprintf(fpout,"%f ",halo.c_star);
      fprintf(fpout,"%f ",halo.Eax_star);
      fprintf(fpout,"%f ",halo.Eay_star);
      fprintf(fpout,"%f ",halo.Eaz_star);
      fprintf(fpout,"%f ",halo.Ebx_star);
      fprintf(fpout,"%f ",halo.Eby_star);
      fprintf(fpout,"%f ",halo.Ebz_star);
      fprintf(fpout,"%f ",halo.Ecx_star);
      fprintf(fpout,"%f ",halo.Ecy_star);
      fprintf(fpout,"%f ",halo.Ecz_star);
      fprintf(fpout,"%g ",halo.Ekin_star);
      fprintf(fpout,"%g ",halo.Epot_star);
    }
    if(halo.numColumns > 83) {
      fprintf(fpout,"%f ",halo.mean_z_gas);
      fprintf(fpout,"%f ",halo.mean_z_star);
    }
    fprintf(fpout,"\n");
  } // if(MassCut)
}



/*=================================================================================================
 * main()
 *=================================================================================================*/
int main(argc,argv)
int argc;
char **argv;
{   
  char   outfile[2048], **infile;
  char   prefix[2048], suffix[2048], suffix_ascii[2048];
  char *halofile,*partfile;
  int    i, slen, ftype, nfiles;

  fprintf(stderr,"======================================================================\n");
  fprintf(stderr," convert files generated by AHF when using -DAHFbinary to ASCII files\n");
  fprintf(stderr,"   (the code also concatenates all catalogues when run in MPI mode)\n");
  fprintf(stderr,"======================================================================\n");
  
  sprintf(halofile,"/export/research/virgo/Boyd/testcurie/6.418_AHF_halos_cubepm_domain_0_halos.dat_bin");
  sprintf(partfile,"/export/research/virgo/Boyd/testcurie/6.418_AHF_halos_cubepm_domain_0_pids.dat_bin");
  load_halo_catalogue_binary(halofile, partfile);
}
  

void load_halo_catalogue_binary(char *halofile, char *partfile )
{
  FILE *fphalo,*fppart;
  
  fphalo = fopen(halofile,"rb");
  fppart = fopen(partfile,"rb");
  fclose(fphalo);
  read_AHF_binary(FILE *fphalo, FILE *fppart)
  fclose(fppart);
}
/*=================================================================================================
 * convert_halos()
 *=================================================================================================*/

void  read_AHF_binary(FILE *fphalo, FILE *fppart)
{
  uint64_t numHalos,numHaloFromPartFile;
  uint32_t numColumns;
  uint64_t i;
  int32_t  one;
  int      swap=0;
  halo_t   halo;
#ifdef SUSSEXBIGRUN
  double_t         energy;
#endif
  // figure out swap status
  fread(&one, sizeof(int32_t), 1, fphalo);
  if(one == 1)   swap = 0;
  else           swap = 1;
  // figure out swap status
  fread(&one, sizeof(int32_t), 1, fppart);
   if(one == 1)    swap = 0;
  else            swap = 1;

  ReadULong(fppart, &numHaloFromPartFile,   swap);
  ReadUInt (fppart, &numColumns, swap);
  printf("particle: nhalo = %ld\n",numHaloFromPartFile);
  ReadULong(fphalo, &numHalos,   swap);
  ReadUInt (fphalo, &numColumns, swap); 
  printf("particle: nhalo = %ld\n",numHalos);
  exit(0);


#ifdef VERBOSE
  fprintf(stderr,"o reading %ld halos from file (swap=%d,numColumns=%d)\n",(long unsigned)numHalos,swap,numColumns);
#endif

  // read in halo properties
  for(i=0; i<numHalos; i++) {
    ReadULong(fphalo, &halo.ID,           swap);    // ID(1)
    ReadULong(fphalo, &halo.hostHalo,     swap);    // hostHalo(2)
    ReadUInt (fphalo, &halo.numSubStruct, swap);    // numSubStruct(3)
    ReadFloat(fphalo, &halo.Mvir,         swap);    // Mvir(4)
    ReadUInt (fphalo, &halo.npart,        swap);    // npart(5)
    ReadFloat(fphalo, &halo.Xc,           swap);    // Xc(6)
    ReadFloat(fphalo, &halo.Yc,           swap);    // Yc(7)
    ReadFloat(fphalo, &halo.Zc,           swap);    // Zc(8)
    ReadFloat(fphalo, &halo.VXc,          swap);    // VXc(9)
    ReadFloat(fphalo, &halo.VYc,          swap);    // VYc(10)
    ReadFloat(fphalo, &halo.VZc,          swap);    // VZc(11)
    ReadFloat(fphalo, &halo.Rvir,         swap);    // Rvir(12)
    ReadFloat(fphalo, &halo.Rmax,         swap);    // Rmax(13)
    ReadFloat(fphalo, &halo.r2,           swap);    // r2(14)
    ReadFloat(fphalo, &halo.mbp_offset,   swap);    // mbp_offset(15)
    ReadFloat(fphalo, &halo.com_offset,   swap);    // com_offset(16)
    ReadFloat(fphalo, &halo.Vmax,         swap);    // Vmax(17)
    ReadFloat(fphalo, &halo.v_esc,        swap);    // v_esc(18)
    ReadFloat(fphalo, &halo.sigV,         swap);    // sigV(19)
    ReadFloat(fphalo, &halo.lambda,       swap);    // lambda(20)
    ReadFloat(fphalo, &halo.lambdaE,      swap);    // lambdaE(21)
    ReadFloat(fphalo, &halo.Lx,           swap);    // Lx(22)
    ReadFloat(fphalo, &halo.Ly,           swap);    // Ly(23)
    ReadFloat(fphalo, &halo.Lz,           swap);    // Lz(24)
    ReadFloat(fphalo, &halo.b,            swap);    // b(25)
    ReadFloat(fphalo, &halo.c,            swap);    // c(26)
    ReadFloat(fphalo, &halo.Eax,          swap);    // Eax(27)
    ReadFloat(fphalo, &halo.Eay,          swap);    // Eay(28)
    ReadFloat(fphalo, &halo.Eaz,          swap);    // Eaz(29)
    ReadFloat(fphalo, &halo.Ebx,          swap);    // Ebx(30)
    ReadFloat(fphalo, &halo.Eby,          swap);    // Eby(31)
    ReadFloat(fphalo, &halo.Ebz,          swap);    // Ebz(32)
    ReadFloat(fphalo, &halo.Ecx,          swap);    // Ecx(33)
    ReadFloat(fphalo, &halo.Ecy,          swap);    // Ecy(34)
    ReadFloat(fphalo, &halo.Ecz,          swap);    // Ecz(35)
    ReadFloat(fphalo, &halo.ovdens,       swap);    // ovdens(36)
    ReadUInt (fphalo, &halo.nbins,        swap);    // nbins(37)
    ReadFloat(fphalo, &halo.fMhires,      swap);    // fMhires(38)
    ReadFloat(fphalo, &halo.Ekin,         swap);    // Ekin(39)
    ReadFloat(fphalo, &halo.Epot,         swap);    // Epot(40)
    ReadFloat(fphalo, &halo.SurfP,        swap);    // SurfP(41)
    ReadFloat(fphalo, &halo.Phi0,         swap);    // Phi0(42)
    ReadFloat(fphalo, &halo.cNFW,         swap);    // cNFW(43)
    if(numColumns > 43) {
      ReadUInt (fphalo, &halo.n_gas,       swap);    // n_gas(44)
      ReadFloat(fphalo, &halo.M_gas,       swap);    // M_gas(45)
      ReadFloat(fphalo, &halo.lambda_gas,  swap);    // lambda_gas(46)
      ReadFloat(fphalo, &halo.lambdaE_gas, swap);    // lambdaE_gas(47)
      ReadFloat(fphalo, &halo.Lx_gas,      swap);    // Lx_gas(48)
      ReadFloat(fphalo, &halo.Ly_gas,      swap);    // Ly_gas(49)
      ReadFloat(fphalo, &halo.Lz_gas,      swap);    // Lz_gas(50)
      ReadFloat(fphalo, &halo.b_gas,       swap);    // b_gas(51)
      ReadFloat(fphalo, &halo.c_gas,       swap);    // c_gas(52)
      ReadFloat(fphalo, &halo.Eax_gas,     swap);    // Eax_gas(53)
      ReadFloat(fphalo, &halo.Eay_gas,     swap);    // Eay_gas(54)
      ReadFloat(fphalo, &halo.Eaz_gas,     swap);    // Eaz_gas(55)
      ReadFloat(fphalo, &halo.Ebx_gas,     swap);    // Ebx_gas(56)
      ReadFloat(fphalo, &halo.Eby_gas,     swap);    // Eby_gas(57)
      ReadFloat(fphalo, &halo.Ebz_gas,     swap);    // Ebz_gas(58)
      ReadFloat(fphalo, &halo.Ecx_gas,     swap);    // Ecx_gas(59)
      ReadFloat(fphalo, &halo.Ecy_gas,     swap);    // Ecy_gas(60)
      ReadFloat(fphalo, &halo.Ecz_gas,     swap);    // Ecz_gas(61)
      ReadFloat(fphalo, &halo.Ekin_gas,    swap);    // Ekin_gas(62)
      ReadFloat(fphalo, &halo.Epot_gas,    swap);    // Epot_gas(63)
      ReadUInt (fphalo, &halo.n_star,       swap);    // n_star(64)
      ReadFloat(fphalo, &halo.M_star,       swap);    // M_star(65)
      ReadFloat(fphalo, &halo.lambda_star,  swap);    // lambda_star(66)
      ReadFloat(fphalo, &halo.lambdaE_star, swap);    // lambdaE_star(67)
      ReadFloat(fphalo, &halo.Lx_star,      swap);    // Lx_star(68)
      ReadFloat(fphalo, &halo.Ly_star,      swap);    // Ly_star(69)
      ReadFloat(fphalo, &halo.Lz_star,      swap);    // Lz_star(70)
      ReadFloat(fphalo, &halo.b_star,       swap);    // b_star(71)
      ReadFloat(fphalo, &halo.c_star,       swap);    // c_star(72)
      ReadFloat(fphalo, &halo.Eax_star,     swap);    // Eax_star(73)
      ReadFloat(fphalo, &halo.Eay_star,     swap);    // Eay_star(74)
      ReadFloat(fphalo, &halo.Eaz_star,     swap);    // Eaz_star(75)
      ReadFloat(fphalo, &halo.Ebx_star,     swap);    // Ebx_star(76)
      ReadFloat(fphalo, &halo.Eby_star,     swap);    // Eby_star(77)
      ReadFloat(fphalo, &halo.Ebz_star,     swap);    // Ebz_star(78)
      ReadFloat(fphalo, &halo.Ecx_star,     swap);    // Ecx_star(79)
      ReadFloat(fphalo, &halo.Ecy_star,     swap);    // Ecy_star(80)
      ReadFloat(fphalo, &halo.Ecz_star,     swap);    // Ecz_star(81)
      ReadFloat(fphalo, &halo.Ekin_star,    swap);    // Ekin_star(82)
      ReadFloat(fphalo, &halo.Epot_star,    swap);    // Epot_star(83)
    }
    if(numColumns > 83) {
      ReadFloat(fphalo, &halo.mean_z_gas,    swap);    // mean_z_gas(84)
      ReadFloat(fphalo, &halo.mean_z_star,   swap);    // mean_z_star(85)
    }
    
    //=================================================================================
    // write halo properties
    //=================================================================================
    halo.numColumns = numColumns;

    ReadULong(fppart, &npart, swap);
    printf("%ld\n",(long unsigned)npart);
    for(ipart=0; ipart<npart; ipart++) {
      ReadULong(fppart, &id, swap);
      fprintf(fpout,"%ld ",(long unsigned)id);
      if(numColumns>1) {
#ifdef SUSSEXBIGRUN
	ReadFloat(fppart, &energy, swap);
	fprintf(fpout, "%g", (float)energy);
#else
        ReadInt(fppart, &ptype, swap);
        fprintf(fpout,"%d",(int)ptype);
#endif
      }
      printf("\n");
    }
    
  } // for(numHalos)
}


/*=================================================================================================
 * get_TotalNumHalos_from_particles()
 *=================================================================================================*/
hid_t get_TotalNumHalos_from_particles(int nfiles, char** infile)
{
  uint64_t       FileNumHalos, TotalNumHalos;
  int            ifile;
  int32_t        one;
  int            swap;
  FILE          *fphalo;
  
  TotalNumHalos = 0;
  
  for(ifile=0; ifile<nfiles; ifile++) {
    
    // open input file
    fphalo = fopen(infile[ifile],"rb");
    if(fphalo == NULL) {
      fprintf(stderr,"FATAL: cannot open %s for writing\n",infile[ifile]);
      exit(0);
    }
    
    // figure out swap status
    fread(&one, sizeof(int32_t), 1, fphalo);
    if(one == 1)   swap = 0;
    else           swap = 1;
    
    ReadULong(fphalo, &FileNumHalos,   swap);
    TotalNumHalos += FileNumHalos;
    
    fclose(fphalo);
  }
  
#ifdef VERBOSE
  fprintf(stderr,"o found %ld halos across all files\n",TotalNumHalos);
#endif
  
  return TotalNumHalos;
}

/*
 Read a possibly byte swapped integer
 */
int ReadInt(FILE *fptr,int *n,int swap)
{
  unsigned char *cptr,tmp;
  
  if(sizeof(int) != 4)
   {
    fprintf(stderr,"ReadInt: sizeof(int)=%ld and not 4\n",sizeof(int));
    exit(0);
   }
  
  if (fread(n,4,1,fptr) != 1)
    return(FALSE);
  if (swap) {
    cptr = (unsigned char *)n;
    tmp     = cptr[0];
    cptr[0] = cptr[3];
    cptr[3] = tmp;
    tmp     = cptr[1];
    cptr[1] = cptr[2];
    cptr[2] = tmp;
  }
  return(TRUE);
}

/*
 Read a possibly byte swapped unsigned integer
 */
int ReadUInt(FILE *fptr,unsigned int *n,int swap)
{
  unsigned char *cptr,tmp;
  
  if(sizeof(int) != 4)
   {
    fprintf(stderr,"ReadInt: sizeof(int)=%ld and not 4\n",sizeof(int));
    exit(0);
   }
  
  if (fread(n,4,1,fptr) != 1)
    return(FALSE);
  if (swap) {
    cptr = (unsigned char *)n;
    tmp     = cptr[0];
    cptr[0] = cptr[3];
    cptr[3] = tmp;
    tmp     = cptr[1];
    cptr[1] = cptr[2];
    cptr[2] = tmp;
  }
  return(TRUE);
}

/*
 Read a possibly byte swapped unsigned long integer
 */
int ReadULong(FILE *fptr,unsigned long *n,int swap)
{
  unsigned char *cptr,tmp;
  
  if(sizeof(unsigned long) == 4)
   {
    if (fread(n,4,1,fptr) != 1)
      return(FALSE);
    if (swap) {
      cptr = (unsigned char *)n;
      tmp     = cptr[0];
      cptr[0] = cptr[3];
      cptr[3] = tmp;
      tmp     = cptr[1];
      cptr[1] = cptr[2];
      cptr[2] = tmp;
    }
   }
  else if(sizeof(unsigned long) == 8)
   {
    if (fread(n,8,1,fptr) != 1)
      return(FALSE);
    if (swap) {
      cptr = (unsigned char *)n;
      tmp     = cptr[0];
      cptr[0] = cptr[7];
      cptr[7] = tmp;
      tmp     = cptr[1];
      cptr[1] = cptr[6];
      cptr[6] = tmp;
      tmp     = cptr[2];
      cptr[2] = cptr[5];
      cptr[5] = tmp;
      tmp     = cptr[3];
      cptr[3] = cptr[4];
      cptr[4] = tmp;
    }
   }
  else
   {
    fprintf(stderr,"ReadULong: something wrong...cannot read long\n");
    exit(0);
   }
  
  return(TRUE);
}

/*
 Read a possibly byte swapped floating point number
 Assume IEEE format
 */
int ReadFloat(FILE *fptr,double_t *n, int swap)
{
  unsigned char *cptr,tmp;
  
  if(sizeof(float) != 4)
   {
    fprintf(stderr,"ReadFloat: sizeof(float)=%ld and not 4\n",sizeof(float));
    exit(0);
   }
  
  if (fread(n,4,1,fptr) != 1)
    return(FALSE);
  if (swap)
   {
    cptr = (unsigned char *)n;
    tmp     = cptr[0];
    cptr[0] = cptr[3];
    cptr[3] = tmp;
    tmp     = cptr[1];
    cptr[1] = cptr[2];
    cptr[2] = tmp;
   }
  return(TRUE);
}

