CREATE TABLE GALAXIES (
 type INTEGER NOT NULL 
,  haloIndex INTEGER NOT NULL 
,  snapNum INTEGER NOT NULL 
,  lookBackTimeToSnap REAL NOT NULL 
,  centralMvir REAL NOT NULL 
,  pos_1 REAL NOT NULL 
,  pos_2 REAL NOT NULL 
,  pos_3 REAL NOT NULL 
,  vel_1 REAL NOT NULL 
,  vel_2 REAL NOT NULL 
,  vel_3 REAL NOT NULL 
,  len INTEGER NOT NULL 
,  mvir REAL NOT NULL 
,  rvir REAL NOT NULL 
,  vvir REAL NOT NULL 
,  vmax REAL NOT NULL 
,  gasSpin_1 REAL NOT NULL 
,  gasSpin_2 REAL NOT NULL 
,  gasSpin_3 REAL NOT NULL 
,  stellarSpin_1 REAL NOT NULL 
,  stellarSpin_2 REAL NOT NULL 
,  stellarSpin_3 REAL NOT NULL 
,  infallVmax REAL NOT NULL 
,  infallSnap INTEGER NOT NULL 
,  hotRadius REAL NOT NULL 
,  oriMergTime REAL NOT NULL 
,  mergTime REAL NOT NULL 
,  distanceToCentralGal_1 REAL NOT NULL 
,  distanceToCentralGal_2 REAL NOT NULL 
,  distanceToCentralGal_3 REAL NOT NULL 
,  coldGas REAL NOT NULL 
,  bulgeMass REAL NOT NULL 
,  diskMass REAL NOT NULL 
,  hotGas REAL NOT NULL 
,  ejectedMass REAL NOT NULL 
,  blackHoleMass REAL NOT NULL 
,  blackHoleGas REAL NOT NULL 
,  iCM REAL NOT NULL 
,  metalsColdGas REAL NOT NULL 
,  metalsBulgeMass REAL NOT NULL 
,  metalsDiskMass REAL NOT NULL 
,  metalsHotGas REAL NOT NULL 
,  metalsEjectedMass REAL NOT NULL 
,  metalsICM REAL NOT NULL 
,  sfr REAL NOT NULL 
,  sfrBulge REAL NOT NULL 
,  xrayLum REAL NOT NULL 
,  bulgeSize REAL NOT NULL 
,  stellarDiskRadius REAL NOT NULL 
,  gasDiskRadius REAL NOT NULL 
,  cosInclination REAL NOT NULL 
,  disruptOn INTEGER NOT NULL 
,  mergeOn INTEGER NOT NULL 
,  coolingRadius REAL NOT NULL 
,  quasarAccretionRate REAL NOT NULL 
,  radioAccretionRate REAL NOT NULL 
,  obsMag_1 REAL NOT NULL 
,  obsMag_2 REAL NOT NULL 
,  obsMag_3 REAL NOT NULL 
,  obsMag_4 REAL NOT NULL 
,  obsMag_5 REAL NOT NULL 
,  obsMagBulge_1 REAL NOT NULL 
,  obsMagBulge_2 REAL NOT NULL 
,  obsMagBulge_3 REAL NOT NULL 
,  obsMagBulge_4 REAL NOT NULL 
,  obsMagBulge_5 REAL NOT NULL 
,  obsMagDust_1 REAL NOT NULL 
,  obsMagDust_2 REAL NOT NULL 
,  obsMagDust_3 REAL NOT NULL 
,  obsMagDust_4 REAL NOT NULL 
,  obsMagDust_5 REAL NOT NULL 
)
